apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
    - mesh
    - all
  hosts:
    - httpbin
    - httpbin.imroc.cc
  http:
    - match:
        - headers:
            cookie:
              regex: "^(.*?;)?(email=[^;]+@imroc.cc)(;.*)?$"
      route:
        - destination:
            host: httpbin
            subset: v1
          weight: 90
        - destination:
            host: httpbin
            subset: v2
          weight: 10
    - route:
        - destination:
            host: httpbin
            subset: v1
